### ISSUE TITLE
Source maps are not linked correctly by Sentry

### ISSUE THREAD

**Issue by StErMi** [getsentry/sentry-capacitor#90] opened 2021-10-05 09:50 UTC
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io) 

Which SDK and version?

```
    "@sentry/capacitor": "^0.4.0",
    "@sentry/react": "^6.11.0",
    "@sentry/tracing": "^6.11.0",
```

### Description

Source maps are not linked correctly by Sentry and I'm unable to understand how to fix the code.
This is the error trace

```
RangeError: Invalid time value
  at Z(app:///static/js/2.8a9aba35.chunk.js:2:718874)
  at un(app:///static/js/main.b1e0cf1d.chunk.js:1:70866)
  at ? (app:///static/js/main.b1e0cf1d.chunk.js:1:71066)
  at ? (app:///static/js/main.b1e0cf1d.chunk.js:1:71975)
  at ri(app:///static/js/main.b1e0cf1d.chunk.js:1:87954)
  at ou(app:///static/js/2.8a9aba35.chunk.js:2:786602)
  at Ga(app:///static/js/2.8a9aba35.chunk.js:2:839060)
  at ws(app:///static/js/2.8a9aba35.chunk.js:2:826234)
  at Ss(app:///static/js/2.8a9aba35.chunk.js:2:826162)
  at Cs(app:///static/js/2.8a9aba35.chunk.js:2:826025)
  at ms(app:///static/js/2.8a9aba35.chunk.js:2:822991)
  at ? (app:///static/js/2.8a9aba35.chunk.js:2:772370)
  at t.unstable_runWithPriority(app:///static/js/2.8a9aba35.chunk.js:2:849789)
  at zo(app:///static/js/2.8a9aba35.chunk.js:2:772147)
  at Yo(app:///static/js/2.8a9aba35.chunk.js:2:772315)
  at Wo(app:///static/js/2.8a9aba35.chunk.js:2:772250)
  at ds(app:///static/js/2.8a9aba35.chunk.js:2:820360)
  at Tu(app:///static/js/2.8a9aba35.chunk.js:2:791927)
  at ? (app:///static/js/2.8a9aba35.chunk.js:2:508500)
  at ? (app:///static/js/2.8a9aba35.chunk.js:2:211534)
  at e.notifyFn(app:///static/js/2.8a9aba35.chunk.js:2:211092)
  at ? (app:///static/js/2.8a9aba35.chunk.js:2:211699)
  at Array.forEach(app:///<anonymous>)
  at ? (app:///static/js/2.8a9aba35.chunk.js:2:211676)
  at e.batchNotifyFn(app:///static/js/2.8a9aba35.chunk.js:2:211128)
  at ? (app:///static/js/2.8a9aba35.chunk.js:2:211648)
  ```

and on the error page sentry say that I'm missing a source file linked to the error

![image](https://user-images.githubusercontent.com/146166/136000623-dbdb49c4-a624-46fa-9147-c83c1e8894ce.png)

  
but if I click on the release associated with the crash (1.3.3) 

![image](https://user-images.githubusercontent.com/146166/136000785-4e094f7c-2ec7-4d07-b3b6-53731ab299ba.png)

and go to  see the source map for that release related to the sentry crash (1.3.3) I can see those source map for file 

![image](https://user-images.githubusercontent.com/146166/136000467-5e5c6f7b-8cd8-4155-be57-56f70a429cbf.png)

what's the problem? How can I solve it?

**Comment by jennmueng** [comment] 2021-10-06 00:42
@StErMi You will also need to set a `dist` on your sourcemaps and the event for it to correctly be linked.

**Comment by StErMi** [comment] 2021-10-06 05:24
> @StErMi You will also need to set a `dist` on your sourcemaps and the event for it to correctly be linked.

could you please point me out to the part of the documentation that explains it?

**Comment by Sampath-Lokuge** [comment] 2022-01-03 09:04
Any update here please? I have the same issue.

**Comment by albertinad** [comment] 2022-01-06 20:47
Any update on this? I have the same issue but with Android.

**Comment by jennmueng** [comment] 2022-01-07 21:25
@albertinad @Sampath-Lokuge @StErMi 
https://docs.sentry.io/platforms/javascript/sourcemaps/troubleshooting_js/#verify-artifact-distribution-value-matches-value-configured-in-your-sdk

**Comment by bruno-garcia** [comment] 2022-01-11 22:21
Is this a dupe of https://github.com/getsentry/sentry-capacitor/issues/90?

**Comment by StErMi** [comment] 2022-01-12 06:10
> Is this a dupe of #90?

I didn't use the same github issue because this issue was about not being able to associate the sourcemaps with the code, the #90 is about wrong association

**Comment by bruno-garcia** [comment] 2022-02-03 19:08
Can we please have a repro for this? A link to a GitHub repo that we can follow the steps and reach thsi issue so we can debug it?

**Comment by jwt02180** [comment] 2022-03-17 16:56
I have the same issue, and I've created a [sample](https://github.com/jwt02180/sentry-sourcemaps-issue) Ionic6/Angular13/Capacitor3 application that demonstrates the problem.
The [README](https://github.com/jwt02180/sentry-sourcemaps-issue/blob/main/README.md) has all the steps I followed to get setup and screenshots of the issue.
I also included a link to my Sentry [event](https://sentry.io/organizations/jamesontaylor/issues/3108472946/events/6faefbe2d6ee4722b7f55dec77f0be90/?project=6262714) there if you have access to view those (linking here again for convenience).

Let me know if you need anymore information from me to get this resolved.

**Comment by lucas-zimerman** [comment] 2022-04-12 18:15
Thanks for the sample!, we'll investigate it and give a feedback soon.

**Comment by lucas-zimerman** [comment] 2022-04-14 14:27
On the given sample, you're uploading the www source maps that has minified files uploaded to sentry using Sentry Cli AND ionic serve uses different files, if you host the files built into the www folder you'll noticed the code will be correctly linked:
https://sentry.io/share/issue/18783b46da1141f1a4735f8a7afb2b00/

ionic serve stack trace
```
Error: Test Thrown Error
  at HomePage.ionViewDidEnter(/src_app_home_home_module_ts.js:104:15)
  at HTMLElement.handler(/vendor.js:6267:48)
  at HTMLElement.sentryWrapped(/vendor.js:17689:17)
  at _ZoneDelegate.push.3484._ZoneDelegate.invokeTask(/polyfills.js:3589:35)
  at Object.onInvokeTask(/vendor.js:94052:33)
...
```
Same error from www
```
Error: Test Thrown Error
  at n.ionViewDidEnter(app:///:8080/4851.1c32e260bf57367e.js:1:262)
  at HTMLElement.Re(app:///:8080/main.8f52b672fcdd06fc.js:1:110561)
  at HTMLElement.h(app:///:8080/main.8f52b672fcdd06fc.js:1:75140)
  at v.invokeTask(app:///:8080/polyfills.f914d6d172771193.js:1:8370)
  at Object.onInvokeTask(app:///:8080/main.8f52b672fcdd06fc.js:1:336431)
```

In order for the ionic serve to be linked, the output rules for ionic build must match the ones used for ionic serve, as an example on your sample, I altered the following lines on angular.json, built it with ionic and then sent the source maps with sentry cli
![image](https://user-images.githubusercontent.com/8229322/163409811-8c6bf249-aa7f-4b1f-a5af-711e62631f88.png)

after that I ran ionic serve and opened the website on `http://127.0.0.1:8100/` (localhost:8100 is producing slightly different stack traces so it's not getting mapped, I'll investigate it later) and the error got linked with the correct source maps uploaded.

**Comment by lucas-zimerman** [comment] 2022-04-14 14:31
@StErMi I think you're running from localhost, could you try from 127.0.0.1?

**Comment by lucas-zimerman** [comment] 2022-05-10 17:46
Closing this issue, feel free to reopen it if needed.

**Closed by lucas-zimerman** 2022-05-10 17:46 UTC
Labels: sourcemaps, Platform: Capacitor, Effort: Small, Impact: Medium
