### ISSUE TITLE
Version mismatch between @sentry/javascript packages installed by user and the @sentry/capacitor package.

### ISSUE THREAD

**Issue by squio** [getsentry/sentry-capacitor#66] opened 2021-07-28 09:45 UTC
### Environment

How do you use Sentry?
- Sentry SaaS (sentry.io)

Which SDK and version?
- Ionic/Angular 5.6.4 
- Angular 11.2.9
- Capacitor 3.0.1
- "@sentry/angular": "^6.10.0",
- "@sentry/capacitor": "^0.3.0",

### Steps to Reproduce

Implement Hello World example **as per git README instructions, not onboarding example which looks outdated**

All relevant code in app-module.ts:

```ts
import {ErrorHandler, Injectable, NgModule} from '@angular/core';
import * as Sentry from "@sentry/capacitor";
import { init as sentryAngularInit, createErrorHandler }  from "@sentry/angular";
// ...

Sentry.init({
    dsn: 'https://gsdhgdshghdsds.ingest.sentry.io/32444532',
}, sentryAngularInit);
Sentry.captureMessage('Hello, world!');
// ...

@NgModule({
    declarations: [
        AppComponent,
    ],
    entryComponents: [],
    imports: [
// ...
       ],
    providers: [
        WebView,
//...
        {
            provide: ErrorHandler,
            useValue: createErrorHandler(),
        },
    ],
    bootstrap: [AppComponent]
})
export class AppModule
{
}
```

Build for Android using Android studio and the following steps:
- ionic cap sync android
- build in Android studio
- run on real device (not emulator)

### Expected Result

Just one issue: `Hello, world!` from `http://localhost/`
And maybe a lot of other exceptions caused by my code ;-)

### Actual Result

Apart from the one Hello World there are many exceptions from Sentry itself: `taskProducer is not a function`

There are 50 events of this issue in just one App launch without any further interacetion

![Screenshot 2021-07-28 at 11-43-43 TypeError taskProducer is not a function](https://user-images.githubusercontent.com/169410/127301455-6610f5c8-c1b2-4ff6-b0c1-7130b4cb83d1.png)

**Comment by squio** [comment] 2021-07-28 11:17
Running the same source on iOS gives the same issue with some more detail:

Steps:
- `ionic cap sync ios`
- build and run app from Xcode (latest release Version 12.5.1)
- app is running on a real iPhone, not emulator (iOS up to date 14.7.1)

Result:

```
TypeError

taskProducer is not a function. (In 'taskProducer()', 'taskProducer' is an instance of ZoneAwarePromise)
```

**Comment by WIStudent** [comment] 2021-07-28 15:23
I just tried to migrate to @sentry/capacitor and also got these errors. It seems to be caused by this change https://github.com/getsentry/sentry-javascript/pull/3744 in the @sentry/utils package. 
https://github.com/getsentry/sentry-capacitor/blob/e566834f89feabe58b3168d0eedcef1158357877/src/transports/native.ts#L20
passes a Promise but `PromiseBuffer.add` expects a function that returns a Promise since version 6.8. In theory downgrading to 6,7,2 should fix it as a workaround, but that is easier said than done with how npm handles version ranges and deduplicates packages.

**Comment by WIStudent** [comment] 2021-07-28 15:36
Ok, I can confirm that these erros do not occur when downgrading all other sentry packages (especially @sentry/utils) to 6.7.2. So this might be a possible workaround until it is fixed in @sentry/capacitor.

**Comment by jennmueng** [comment] 2021-07-29 17:11
@WIStudent @squio You will need to use the same version of the `@sentry/*` packages that the `@sentry/capacitor` package, such as for this latest version should be `6.5.0`.

I added this bug tag not that there is a bug in the SDK but that this is an issue we need to solve on how to avoid mismatched versions like this in the future, be it better documentation or change the way you would install this SDK.

**Comment by WIStudent** [comment] 2021-07-29 18:57
By the way I just tried what happens when I install `@sentry/capacitor` in an empty project. npm@7 still resolves the other sentry dependencies with `6.10.0` because that is the newest version that still fits the `^6.5.0` range.
```
$ npm list --depth 1
sentry-test@1.0.0
└─┬ @sentry/capacitor@0.3.0
  ├── @capacitor/core@3.1.2
  ├── @sentry/browser@6.10.0
  ├── @sentry/core@6.10.0
  ├── @sentry/hub@6.10.0
  ├── @sentry/integrations@6.10.0
  ├── @sentry/tracing@6.10.0
  ├── @sentry/types@6.10.0
  ├── @sentry/utils@6.10.0
  ├── @sentry/wizard@1.2.10
  └── promise@8.1.0
```
So in order to force version `6.5.0` of the other sentry dependencies the caret definitely needs to be removed.

**Comment by jennmueng** [comment] 2021-07-30 04:55
@WIStudent Yep we will remove the carets, but I didn't know about the optional peerdependencies. I will try that out.

**Closed** 2021-08-23 20:36 UTC
Labels: bug

**Comment by squio** [comment] 2021-08-24 08:13
Nice to see this has been merged 🎉 
Will there be a new release any time soon?

**Comment by jennmueng** [comment] 2021-08-24 14:55
@squio Expect `0.4.0` very soon either today or in a following day.
