### ISSUE TITLE
Peer Dependencies npm install --save @Sentry/capacitor Fails

### ISSUE THREAD

**Issue by 15aabruzzese** [getsentry/sentry-capacitor#405] opened 2023-07-05 17:06 UTC
### Environment

Angular 16: I can successfully download @sentry/angular-ivy 
Capacitor 5:
Iconic 7:
npm 9.5.1
node 18.16

### Steps to Reproduce

1. Following the installation guide for angular/capacitor set up
2. `npm install --save @sentry/capacitor @sentry/angular-ivy` or `npm install --save @sentry/capacitor` or `npm install --save @sentry/capacitor --force`
3.  installation fails

![image](https://github.com/getsentry/sentry-capacitor/assets/96092264/32512369-1b63-4750-860e-e0ae0e40ca46)

### Expected Result
The npm install would be successful

### Actual Result
install fails (see screenshots)

Current Dependencies: 
"dependencies": {
    "@angular/common": "^16.0.3",
    "@angular/core": "^16.0.3",
    "@angular/forms": "^16.0.3",
    "@angular/platform-browser": "^16.0.3",
    "@angular/platform-browser-dynamic": "^16.0.3",
    "@angular/router": "^16.0.3",
    "@awesome-cordova-plugins/app-version": "^6.3.0",
    "@capacitor-community/firebase-analytics": "^5.0.1",
    "@capacitor/android": "^5.0.4",
    "@capacitor/app": "^5.0.2",
    "@capacitor/camera": "^5.0.2",
    "@capacitor/core": "^5.0.5",
    "@capacitor/haptics": "^5.0.2",
    "@capacitor/ios": "^5.0.4",
    "@capacitor/keyboard": "^5.0.2",
    "@capacitor/status-bar": "^5.0.2",
    "@ionic/angular": "^7.0.9",
    "@ionic/pwa-elements": "^3.1.1",
    "@ionic/storage-angular": "^4.0.0",
    "@trapezedev/configure": "^7.0.10",
    "capacitor-native-settings": "^5.0.0",
    "cordova-plugin-app-version": "^0.1.14",
    "envsub": "^4.1.0",
    "ionicons": "^7.1.1",
    "ngx-mask": "^16.0.8",
    "rxjs": "^7.8.1",
    "swiper": "^8.4.6",
    "tslib": "^2.5.2",
    "zone.js": "^0.13.0"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^16.0.3",
    "@angular-eslint/builder": "^16.0.3",
    "@angular-eslint/eslint-plugin": "^16.0.3",
    "@angular-eslint/eslint-plugin-template": "^16.0.3",
    "@angular-eslint/template-parser": "^16.0.3",
    "@angular/cli": "^16.0.3",
    "@angular/compiler": "*",
    "@angular/compiler-cli": "^16.0.3",
    "@angular/language-service": "^16.0.3",
    "@capacitor/cli": "^5.0.6-nightly-20230627T150701.0",
    "@ionic/angular-toolkit": "^9.0.0",
    "@ionic/cli": "^7.1.1",
    "@types/jasmine": "^4.3.2",
    "@types/jasminewd2": "^2.0.10",
    "@types/node": "^20.2.5",
    "@typescript-eslint/eslint-plugin": "^5.59.8",
    "@typescript-eslint/parser": "^5.59.8",
    "eslint": "^8.41.0",
    "eslint-plugin-import": "^2.27.5",
    "eslint-plugin-jsdoc": "^45.0.0",
    "eslint-plugin-prefer-arrow": "^1.2.3",
    "jasmine-core": "^4.6.0",
    "jasmine-spec-reporter": "^7.0.0",
    "karma": "^6.4.2",
    "karma-chrome-launcher": "^3.2.0",
    "karma-coverage": "^2.2.0",
    "karma-coverage-istanbul-reporter": "^3.0.3",
    "karma-jasmine": "^5.1.0",
    "karma-jasmine-html-reporter": "^2.0.0",
    "prettier": "^2.8.8",
    "protractor": "^7.0.0",
    "ts-node": "^10.9.1",
    "typescript": "^5.0.4"
  },

**Comment by lucas-zimerman** [comment] 2023-07-07 09:29
Does it install with the following command?
`npm install --save-exact @sentry/capacitor@0.12.1 @sentry/angular-ivy@7.56.0 --update-sentry-capacitor`

**Comment by Ionaru** [comment] 2023-07-09 15:45
@lucas-zimerman That results in the same error.

It looks like the `@sentry/angular` peer dependency of `@sentry/capacitor` conflicts with any Angular 16 project, even though `@sentry/angular` is marked as optional. Maybe related to a fix done for https://github.com/npm/cli/issues/4859, but I am not sure.

![image](https://github.com/getsentry/sentry-capacitor/assets/3472373/4c294e79-7701-444a-89f1-71fc9a3ddb81)

I think the simplest fix would be to replace the peer dependency `@sentry/angular` with `@sentry/angular-ivy` in the `@sentry/capacitor` package.

I tried adding overrides to my package.json, but that did not work in this case.

**Comment by mdintouch** [comment] 2023-07-31 13:42
Any plans on getting this fixed?

**Comment by jneterer** [comment] 2023-08-23 13:25
Any update on this?

**Comment by ahunter135** [comment] 2023-09-05 14:09
Made a pr for this: https://github.com/getsentry/sentry-capacitor/pull/458

**Comment by afilp** [comment] 2023-09-18 10:57
@lucas-zimerman Can you please approve and merge the changes so that we can start using the fix soon (with Angular 16)? Thanks a lot!

**Comment by Ionaru** [comment] 2023-09-19 09:37
I was able to install this package by placing overrides in my `package.json`

```json
  "overrides": {
    "@sentry/angular": {
      "@angular/common": "*",
      "@angular/core": "*",
      "@angular/router": "*"
    }
  }
```

**Comment by emelampianakis** [comment] 2023-09-20 10:18
> I was able to install this package by placing overrides in my `package.json`
> 
> ```json
>   "overrides": {
>     "@sentry/angular": {
>       "@angular/common": "*",
>       "@angular/core": "*",
>       "@angular/router": "*"
>     }
>   }
> ```

Did it build with angular 16 using sentry-angular instead angular-ivy?

**Comment by Ionaru** [comment] 2023-09-21 11:11
> Did it build with angular 16 using sentry/angular instead of /angular-ivy?

It builds with `@sentry/angular-ivy`. With those lines added to your `package.json`, the command `npm install --save @sentry/capacitor @sentry/angular-ivy` should succeed.

**Comment by krystofwoldrich** [comment] 2023-09-22 14:22
Hello everyone I've tried to reproduce the issue with a new project and I was unsuccessful.

https://github.com/krystofwoldrich/sentry-capacitor-angular-ivy/blob/64024cf710c47b523bed4a9dd5e7cc26c965c62a/package.json

Could anyone share a minimal reproducible example?

Based on the `peerDependencies` of `sentry-capacitor` the `@sentry/angular` package should not install automatically in projects with Angular 12 and newer.

I used this command to add Sentry `npm install --save --exact @sentry/capacitor@0.12.3 @sentry/angular-ivy@7.64.0`

Without specifying the version of `@sentry/angular-ivy` the latest gets installed which can cause issues with mismatched types with `sentry-capacitor`.

**Comment by emelampianakis** [comment] 2023-09-22 14:26
> Hello everyone I've tried to reproduce the issue with a new project and I was unsuccessful.
> 
> https://github.com/krystofwoldrich/sentry-capacitor-angular-ivy/blob/64024cf710c47b523bed4a9dd5e7cc26c965c62a/package.json
> 
> Could anyone share a minimal reproducible example?
> 
> Based on the `peerDependencies` of `sentry-capacitor` the `@sentry/angular` package should not install automatically in projects with Angular 12 and newer.
> 
> I used this command to add Sentry `npm install --save --exact @sentry/capacitor@0.12.3 @sentry/angular-ivy@7.64.0`
> 
> Without specifying the version of `@sentry/angular-ivy` the latest gets installed which can cause issues with mismatched types with `sentry-capacitor`.

add to package.json

"overrides": {
    "@sentry/angular": {
      "@angular/common": "*",
      "@angular/core": "*",
      "@angular/router": "*"
    }
  }
  
npm install --save @sentry/capacitor@0.12.3 (latest atm)
npm install @sentry/angular-ivy@7.64.0

the angular-ivy should match the javascript version of the sentry/capacitor

**Comment by Ionaru** [comment] 2023-09-24 15:10
I'm also no longer able to reproduce this issue, even with the original reporter's command. Maybe something was fixed on the npm side? I have since upgraded npm to `v10.1.0` where before I was running version 9, I think.

**Comment by krystofwoldrich** [comment] 2023-09-25 08:24
@lonaru Thanks for the message. I've tried with npm 8.19.4 and that worked.

**Comment by krystofwoldrich** [comment] 2023-09-25 08:25
Since we can't reproduce the issue I'm closing this. In case there is a new context or reproducible example, please, comment here and we can reopen it.

**Closed by krystofwoldrich** 2023-09-25 08:25 UTC
Labels: question, Platform: Capacitor
