### ISSUE TITLE
TS2451: Cannot redeclare block-scoped variable

### ISSUE THREAD

**Issue by matthew2564** [getsentry/sentry-capacitor#249] opened 2022-10-24 10:18 UTC
### Is there an existing issue for this?

- [X] I have checked for existing issues https://github.com/getsentry/sentry-javascript/issues
- [X] I have reviewed the documentation https://docs.sentry.io/
- [X] I am using the latest SDK release https://github.com/getsentry/sentry-javascript/releases

### How do you use Sentry?

Sentry Saas (sentry.io)

### Which package are you using?

@sentry/angular

### SDK Version

7.16.0

### Framework Version

Angular 13.3.11 & Ionic 6.3.2

### Steps to Reproduce

Node.js v16.10.x

Typescript 4.5.x

Currently we are using the following versions of Sentry package:
   "@sentry/angular": "^6.19.7",
    "@sentry/capacitor": "^0.6.1",
    "@sentry/tracing": "^6.19.7"

After trying to bump all packages to latest i.e.:
    "@sentry/angular": "^7.16.0",
    "@sentry/capacitor": "^0.10.1",
    "@sentry/tracing": "^7.16.0"

### Expected Result

No error

### Actual Result

I receive the following error:
```
Error: node_modules/@sentry/types/types/globals.d.ts:2:11 - error TS2451: Cannot redeclare block-scoped variable '__DEBUG_BUILD__'.

2     const __DEBUG_BUILD__: boolean;
            ~~~~~~~~~~~~~~~

  node_modules/@sentry/tracing/node_modules/@sentry/types/types/globals.d.ts:2:11
    2     const __DEBUG_BUILD__: boolean;
                ~~~~~~~~~~~~~~~
    '__DEBUG_BUILD__' was also declared here.
```

**Comment by lucas-zimerman** [comment] 2022-10-25 01:10
To fix this you must use a fixed sibling version of angular and tracing
```
"@sentry/angular": "7.13.0",
"@sentry/capacitor": "0.10.1",
"@sentry/tracing": "7.13.0"
```
Additionally, at the moment the SDK is compatible with version 7.13.0.

Hopefully this situation will get clearer on the next versions of Sentry Capacitor

**Comment by lucas-zimerman** [comment] 2022-10-25 13:56
By the way, what if when updating the Sentry packages you would get a message like this
```
This version of Sentry Capacitor is incompatible with the following installed packages:
@sentry/angular version 7.13.0
@sentry/vue version 7.13.0
Please install the mentioned packages with exactly with version 7.15.0 using the below command.
yarn add --exact @sentry/angular@7.15.0 @sentry/vue@7.15.0 
```

Would that be a convenient way of telling you what to do in order to update those packages? (also a similar message if you were using npm for package management)

Ideally it should work out of the box, but unfortunately, it's how the SDK behaves when there's a duplicated sibling package.

**Comment by lforst** [comment] 2022-10-25 14:29
I am backlogging this for the JS SDK team because I'd like to fix this more sustainably. Right now we're polluting the global typescript namespace with the JS SDK.

Here is the origin of the problem: https://github.com/getsentry/sentry-javascript/pull/5155#discussion_r885655812 (Note to self: What looks fishy, probably is)

**Comment by matthew2564** [comment] 2022-10-27 10:16
Just to let you know, fixing the versions as specified above does work - thank you @lucas-zimerman.

**Comment by lnovelli** [comment] 2022-11-25 22:27
Had a very similar issue. I was using `@sentry/electron` 4.1.2 and realized it was relying on `@sentry/types` 7.16.0 under the hood. After I explicitly added  `@sentry/types` 7.16.0 to my `packages.json` it worked like a charm.

**Comment by SerjMalko** [comment] 2023-01-25 21:02
Something has changed?

**Comment by iborschca** [comment] 2023-02-17 23:56
npm install --save-exact @sentry/angular@7.16.0  --update-sentry-capacitor

**Comment by Lilja** [comment] 2023-02-28 15:55
Is it only compatible with `7.13.0` or `7.13.0` and later? I'm having trouble with my node modules `@sentry/types` being `7.31.0`.

**Comment by zarko-tg** [comment] 2023-05-08 23:30
Getting same/similar build error on a Ionic 6 / Angular 16 / Capacitor 4 project. Trying to move from @sentry/angular to @sentry/angular-ivy.
Dependencies used:
"@sentry/angular-ivy": "^7.51.2"
"@sentry/capacitor": "^0.11.3"

```
[ng] Error: node_modules/@sentry/capacitor/node_modules/@sentry/types/types/globals.d.ts:2:11 - error TS2451: Cannot redeclare block-scoped variable '__DEBUG_BUILD__'.
[ng]
[ng] 2     const __DEBUG_BUILD__: boolean;
[ng]             ~~~~~~~~~~~~~~~
[ng]
[ng]   node_modules/@sentry/types/types/globals.d.ts:2:11
[ng]     2     const __DEBUG_BUILD__: boolean;
[ng]                 ~~~~~~~~~~~~~~~
[ng]     '__DEBUG_BUILD__' was also declared here.
[ng]
[ng]
[ng] Error: node_modules/@sentry/types/types/globals.d.ts:2:11 - error TS2451: Cannot redeclare block-scoped variable '__DEBUG_BUILD__'.
[ng]
[ng] 2     const __DEBUG_BUILD__: boolean;
[ng]             ~~~~~~~~~~~~~~~
[ng]
[ng]   node_modules/@sentry/capacitor/node_modules/@sentry/types/types/globals.d.ts:2:11
[ng]     2     const __DEBUG_BUILD__: boolean;
[ng]                 ~~~~~~~~~~~~~~~
[ng]     '__DEBUG_BUILD__' was also declared here.
```

**Comment by zarko-tg** [comment] 2023-05-11 13:26
@chutzemischt I think the problem is that support for Angular 16 comes only with 7.51.0.

**Comment by chutzemischt** [comment] 2023-05-11 14:00
@zarko-tg zarko-tg

You're right, Angular 16 support comes officially with 7.51.0. Didn't saw that. I've a project which is running with Angular 16 and following versions of sentry:

`"@sentry/angular-ivy": "7.50.0"`
`"@sentry/capacitor": "0.11.3"`

Of course the `legacy-peer-deps` has to be set to true.

**Comment by zarko-tg** [comment] 2023-06-22 11:56
This is still a problem, so I opened a new case:
https://github.com/getsentry/sentry-capacitor/issues/394

**Comment by bruno-garcia** [comment] 2023-11-25 19:06
I just hit this problem, Angular 15, build was working fine last I touched this, just changed some unrelated files (outside the SPA) and CI is broken but build locally.

> error TS2451: Cannot redeclare block-scoped variable '__DEBUG_BUILD__'.

https://github.com/dotnet/nuget-trends/actions/runs/6990848438/job/19020769563?pr=245

Any tips how to resolve this?

**Comment by lforst** [comment] 2023-11-27 09:13
@bruno-garcia We can fix this upstream. I'll start working on it today!

**Comment by lforst** [comment] 2023-11-28 11:11
@lucas-zimerman @bruno-garcia We fixed this upstream in the latest JS SDK release so once we update everything this error should be gone for good.

**Comment by bruno-garcia** [comment] 2023-11-28 18:27
Thanks Luca! I'll test it on nuget trends the weekend

**Comment by lucas-zimerman** [comment] 2024-07-30 22:04
The latest Capacitor already points to the JavaScript SDK with the required fix for this so I am closing this issue, if there are any questions, feel free to create a new issue.

**Closed by lucas-zimerman** 2024-07-30 22:04 UTC
Labels: Platform: Capacitor, Type: Bug, Status: Backlog
