### ISSUE TITLE
Known Bug: Stack frames are incorrectly marked with in_app

### ISSUE THREAD

**Issue by jennmueng** [getsentry/sentry-capacitor#43] opened 2021-06-02 16:45 UTC
<img width="780" alt="Screen Shot 2021-06-02 at 11 44 05 PM" src="https://user-images.githubusercontent.com/30991498/120519093-73636200-c3fc-11eb-8461-dba57b11b077.png">

In the image above, the typescript file is marked `in_app: false`, while the JS file is marked `in_app: true`. It should be the other way around.

**Comment by lucas-zimerman** [comment] 2022-05-12 19:51
![image](https://user-images.githubusercontent.com/8229322/168155896-a52fb4c6-32c4-4acb-adb9-9c56771fc699.png)
It isn't quite clear the usage of in_app for Type/JavaScript code, for now all I found was the following mention:

https://github.com/getsentry/sentry-javascript/commit/858c2f7ac627211f8803eb2c6e03418ac3ce610e#diff-6872f62e614276844d459602f9ddbc095baae448ca27e35fcd0d053ea85e97ebR11-R12

My current sugestion for this fix: consider all browser frames as in_app as long as they don't come from vendor.\*.js and polyfills.\*.js.

What do you think @bruno-garcia  and @marandaneto?

**Comment by marandaneto** [comment] 2022-05-13 08:09
@AbhiPrasad or @lobsterkatie might help here, I don't know the inApp logic for JS that well.

**Comment by timfish** [comment] 2022-05-19 02:22
I recently re-worked all the stack parsing code so I can confirm that all browser frames are considered `in_app`.

The capacitor SDK does rewrite frames and override this though:
https://github.com/getsentry/sentry-capacitor/blob/9e38a41dc55a40bb4a848744a904bd00af595509/src/sdk.ts#L45-L73

**Comment by lucas-zimerman** [comment] 2022-05-30 19:40
Closing this since the expected behavior was implemented.

**Closed by lucas-zimerman** 2022-05-30 19:40 UTC
Labels: bug, Platform: Capacitor
